#!/usr/bin/env bash
# configures a new ubuntu machine
sudo apt-get update -y
sudo apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
service nginx start
