#!/usr/bin/env bash
# loops from 1 to 10 and prints bad luck numbers
i=1
while [ $i -le 10 ]
do
    if [[ $i = 4 ]]
	then
	echo 'bad luck'
    elif [[ $i = 8 ]]
	then
	echo 'good luck'
    else
	echo 'Holberton School'
    fi
    (( i++ ))
done
